### ISSUE TITLE
Missing slidebar

### ISSUE THREAD

**Issue by a-Rahmati** [wolfetti/clickup-snap#1]
Hello,

I installed this application via snap. When I open it, there's no sidebar at the left.

original webapp:
![Selection_347](https://user-images.githubusercontent.com/52320192/156875075-1f3fbb68-b6d2-43ec-ab44-591b61085c61.png)

snap application:
![Selection_348](https://user-images.githubusercontent.com/52320192/156875103-03aeef7e-fd92-4bc3-a45f-ef0b4bc4ff0f.png)

How can I enable the sidebar?

Thanks

**Comment by wolfetti** [comment]
Hi, have you tried reloading the page? Sometimes remote updates needs to be reloaded.
[View] -> [Reolad]
or 
[View] -> [Force Reolad]
